### ISSUE TITLE
Autocompletion for enums is cumbersome

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/typescript-static-graphql-server#14]
Autocompletion for enums is not optimal, for example when working with an `orderBy` argument:

Here I wanted to order by `id`, but it didn't work and autocompletion didn't make helpful suggestions:

![image](https://user-images.githubusercontent.com/1780597/34454886-98c0a600-ed74-11e7-8394-b6842290040e.png)

Only by knowing that `orderBy` is of type `UserOrderBy`, I could get helpful suggestions:

![image](https://user-images.githubusercontent.com/1780597/34454888-a5cdffb4-ed74-11e7-8a91-43d4b037a66f.png)

I assume that it's similar for other enum input fields (for example for `createUser(data: {role: USER})`).

**Comment by kbrandwijk** [comment]
@marktani In the latest version of `graphql-static-binding`, all enums are generated as:
```
export type UserOrderBy = 'email_ASC' | 'email_DESC' | ...
```
That makes it easier to use. See https://github.com/supergraphql/graphql-static-binding/issues/9
The advanced boilerplate in the feature-prepare branch of this repo is updated with the last bits.

**Comment by marktani** [comment]
Awesome! Yep in my code it's still exported as a TS enum. Thanks! 🙏

**Comment by kbrandwijk** [comment]
```
graphql create server -b https://github.com/graphql-boilerplates/typescript-static-graphql-server/tree/feature-prepare/advanced
```
